version: "3.7"
services:
  geoweb:
    image: geoweb-dev
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      AUTH_TYPE: developer
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ppassword
      SECRET_KEY_BASE:
      SOLR_URL: http://geosolr:8983/solr/geoweb
      OGC_PROXY_HOST: http://geoserver:8080
      OGC_PROXY_USERNAME: "${GEOSERVER_USER:-admin}"
      OGC_PROXY_PASSWORD: "${GEOSERVER_PASSWORD}"
  geoserver:
    image: docker-geoserver-dev
    ports:
      - "8080:8080"
    depends_on:
      - db
      - geoweb
    volumes:
      - type: volume
        source: geoserver
        target: /opt/geoserver_data
    environment:
      EXTRA_JAVA_OPTS: "-Ds3.properties.location=/opt/geoserver_data/s3.properties"
      GEOSERVER_USER: "${GEOSERVER_USER:-admin}"
      GEOSERVER_PASSWORD: "${GEOSERVER_PASSWORD}"
      MINIO_URL: http://minio:9000/
      MINIO_USER: "${MINIO_USER:-minio}"
      MINIO_PASSWORD: "${MINIO_PASSWORD}"
  geosolr:
    image: docker-geosolr-dev
    ports:
      - "8983:8983"
    environment:
      SOLR_HOME: /var/solr/data
      GEO_CORE: /var/solr/data/geoweb
    volumes:
      - type: volume
        source: geosolr
        target: /var/solr/data
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ACCESS_KEY: "${MINIO_USER:-minio}"
      MINIO_SECRET_KEY: "${MINIO_PASSWORD}"
    volumes:
      - type: volume
        source: s3
        target: /data
  db:
    image: postgis/postgis:11-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ppassword
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
volumes:
  geoserver:
  geosolr:
  s3:
  db:
