version: "3.4"
services:
  web:
    image: geoweb
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      SECRET_KEY_BASE:
      SOLR_URL: http://solr:8983/solr/geoweb
  db:
    image: postgres
  solr:
    image: solr
    command: solr-create -c geoweb -d /solr/conf
    volumes:
      - ./solr/conf:/solr/conf
    ports:
      - 8983:8983
