development:
  backend: http://localhost:8080
  prefix: /geoserver
  username: admin
  password: geoserver
  read_timeout: <%= ENV.fetch("OGC_PROXY_TIMEOUT", 10) %>
production:
  backend: <%= ENV["OGC_PROXY_HOST"] %>
  prefix: /geoserver
  username: <%= ENV["OGC_PROXY_USERNAME"] %>
  password: <%= ENV["OGC_PROXY_PASSWORD"] %>
  read_timeout: <%= ENV.fetch("OGC_PROXY_TIMEOUT", 10) %>
