# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 128868e9e23fde71da548963b3c3ff4678e440ee9e069458725103d148ce0bc71f71a4a9f5d6a986ad30b22f0690cde913a382ba36773d996ffcdc29a5a4cf8e

test:
  secret_key_base: 842fd9e4411d6fba453598a010e4c2f5fc30b6065cea3d124e89e409efa46b34c7f07af262b582f8f14d37e91457831a5799a47f5f5d996821ed98446e370c04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
