### This is the Terraform-generated dev-build.yml workflow for the geoweb-dev app repository ###
name: Dev Container Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: Dev Container Deploy
    uses: mitlibraries/.github/.github/workflows/ecr-shared-deploy-dev.yml@carbon-reqs
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "geoweb-gha-dev"
      ECR: "geoweb-dev"
